var annotated_dup =
[
    [ "Aircraft", "class_aircraft.html", null ],
    [ "AircraftMover", "struct_aircraft_mover.html", null ],
    [ "Application", "class_application.html", null ],
    [ "Command", "struct_command.html", null ],
    [ "CommandQueue", "class_command_queue.html", null ],
    [ "Entity", "class_entity.html", null ],
    [ "FrameResource", "struct_frame_resource.html", null ],
    [ "GameState", "class_game_state.html", null ],
    [ "MaterialData", "struct_material_data.html", null ],
    [ "MenuState", "class_menu_state.html", null ],
    [ "ObjectConstants", "struct_object_constants.html", null ],
    [ "PassConstants", "struct_pass_constants.html", null ],
    [ "PauseState", "class_pause_state.html", null ],
    [ "Player", "class_player.html", null ],
    [ "RenderItem", "struct_render_item.html", null ],
    [ "SceneNode", "class_scene_node.html", null ],
    [ "SpriteNode", "class_sprite_node.html", null ],
    [ "State", "class_state.html", "class_state" ],
    [ "StateStack", "class_state_stack.html", null ],
    [ "TitleState", "class_title_state.html", null ],
    [ "Vertex", "struct_vertex.html", null ],
    [ "World", "class_world.html", null ]
];